language: ruby

rvm:
  - 2.1.8
  - 2.2.4

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile

sudo: false

bundler_args: --no-deployment

script: bundle exec rake test

matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails5.1.gemfile
