rvm:
  - 1.9.3
  - 2.0
  - 2.1
gemfile:
  - gemfiles/rails2.3.gemfile
  - gemfiles/rails3.0.gemfile
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/rails2.3.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails3.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails2.3.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails3.0.gemfile
bundler_args: --no-deployment
script: bundle exec rake test
